project:
  type: website

website:
  title: "Pingfan Hu"
  favicon: favicon.png
  search:
    location: navbar
    type: textbox
    copy-button: true
  navbar:
    left:
      - icon: file-text
        href: blog.qmd
        text: "Blog"
      - icon: person-badge
        href: about.qmd
        text: "About"
      - icon: file-bar-graph
        href: projects.qmd
        text: "Projects"
      - icon: file-earmark-text
        href: lectures.qmd
        text: "Lectures"
        
    right:
      - icon: person-circle
        href: resume.pdf
        text: "Resume"
      - icon: linkedin
        href: https://www.linkedin.com/in/pingfan/
      - icon: github
        href: https://github.com/pingfan0727
      - icon: envelope-at
        href: mailto:pingfan.hu@gwu.edu

format:
  html:
    toc: true
    toc-location: right
    theme: 
      light: [united, theme-light.scss]
      dark: [united, theme-dark.scss]
    css: styles.css
    self-contained: true
    link-external-newwindow: true
    link-external-icon: false

execute: 
  echo: true
  warning: false

editor: visual

