freeze: false
editor: visual

project:
  type: website

format:
  html:
    toc: true
    toc-location: right
    theme: [united, theme.scss]
    css: styles.css
    self-contained: true
    link-external-newwindow: true
    link-external-icon: false
    backgroundcolor: "#F5F2E9"

execute: 
  warning: false

website:
  title: "Pingfan Hu"
  favicon: favicon.png
  search:
    location: navbar
    type: textbox
    copy-button: true
  navbar:
    left:
      - icon: person-badge
        href: about.qmd
        text: "About"
      - icon: file-text
        href: blog.qmd
        text: "Blog"
      - icon: file-bar-graph
        href: projects.qmd
        text: "Projects"
      - icon: person-circle
        href: contents/resume.pdf
        text: "Resume"
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/pingfan/
      - icon: github
        href: https://github.com/pingfan0727
      - icon: envelope-at
        href: mailto:pingfan.hu@gwu.edu





